services:
  - type: web
    name: timetable
    runtime: docker
    plan: free
    envVars:
      - key: TZ
        value: Europe/Prague
      - key: GTFS_SOURCE_URL
        value: http://www.dpmlj.cz/gtfs.zip
